# Changes here will be overwritten by Copier.
_commit: 1.11.0
_src_path: gh:pawamoy/copier-uv
author_email: ketyvagenfeld@gmail.com
author_fullname: Kety Vagenfeld
author_username: ketyvagenfeld
copyright_date: '2025'
copyright_holder: Kety Vagenfeld
copyright_holder_email: ketyvagenfeld@gmail.com
copyright_license: MIT
insiders: false
project_description: ''
project_name: dobot
python_package_command_line_name: dobot
python_package_distribution_name: dobot
python_package_import_name: dobot
repository_name: dobot
repository_namespace: ketyvagenfeld
repository_provider: github.com

